[tool.commitizen]
name = "cz_conventional_commits"
version = "v0.0.0"
tag_format = "v$major.$minor.$patch$prerelease"
bump_message = "release $current_version -> $new_version [skip ci]"
version_files = [".cz.toml", "VERSION"]
update_changelog_on_bump = true
