# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: PR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  entry:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint CLI
        # You may pin to the exact commit or the version.
        # uses: bennypowers/commitlint-gh-actions@e2376695382ef566db685cdf4dbcd144aafb6911
        uses: bennypowers/commitlint-gh-actions@v1.0.1
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.x"

      - name: Install Test dependencies
        run: task get_test_dependencies

      - name: Build
        run: go build -v ./...

      - name: Test
        run: task test_coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt
